### ISSUE TITLE
show case the diversity in our community

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#11]
Starting a community spotlight to our blog or via a podcast, to enable people with a diverse background to explain how they use Symfony and how they made their way into the community

**Comment by sgrabowski** [comment]
Hey! I'm a trans-species attack helicopter ( I identify as Apache ) and would love to write an entry for your blog.

**Comment by lsmith77** [comment]
@sgrabowski thank you for reaching out. would you also be interested in championing the initiative to interview other people in the community and to share where they are coming from?

**Comment by fabpot** [comment]
http://knowyourmeme.com/memes/i-sexually-identify-as-an-attack-helicopter

**Comment by lsmith77** [comment]
ah my mind isn’t deep enough into the meme gutter it seems to get these kinds of responses .. *sigh*

**Comment by javiereguiluz** [comment]
One of the ideas that has been proposed to raise awareness of the diverse community members is a podcast interview introducing them. I think @magnusnordlander and @lsmith77 have been talking about this.

I'd like to ask you to reconsider this idea. The problem is that it's not that common for people to talk good enough English to record a podcast interview. This is specially true for minorities in all Asia, big parts of South America, lots of African countries where English is not official and even lots of European countries where most people have a low English level (Spain, France, Italy, ...)

Maybe you could turn this into written interviews? Most people should have enough level to answer written questions or they can use Google Translate to do it. Something like this -> https://symfony.com/blog/interview-with-pawe-jdrzejewski-founder-of-sylius-project but with more personal questions and some photos.

Thanks for your consideration!

**Comment by lsmith77** [comment]
You raise a very valid point there! I agree that a podcast has the risk of creating a barrier we don’t want.

**Comment by patrickvale** [comment]
I would be very happy to help out with this - I can translate some languages and help with the production or editing of interviews. The [interview with Paweł Jędrzejewski](https://symfony.com/blog/interview-with-pawe-jdrzejewski-founder-of-sylius-project) is an interesting starting point, though as @javiereguiluz suggests it would probably work well with more personal/broad questions and some pictures, perhaps. I've put together a quick list of questions that might be a starting point - I was basically interviewing myself, so they may not be relevant in the slightest! But I paste them here in any case, just in case they are helpful:

* What is your name?
* Where do you live (most of the time)
* When did you first encounter Symfony
* What was your first impression of it?
* What was the first thing you used Symfony for?
* How did that work out?
* What area do you work/study in?
* What do use Symfony for now?
* On a daily basis?
* What is your favourite Symfony feature?
* What are you most looking forward to? (In Symfony, or anything else)
* What would you say to a new Symfony user today?

I wasn't sure whether to include anything about education as while it's interesting, it might put people off who don't have a lot of educational certificates (for example, I have no University degree and it does cause me to be a little hesitant when talking about my educational background) but perhaps this is exactly the place we should be showcasing the huge variety of backgrounds and paths that people have taken to reach the Symfony community. So I'm not sure about that.

It might be good to have a quick 'boilerplate' interview that lots of people could answer quickly, from new-comers to veteran core-team-members, almost like a 'potted biography' but with some interesting (and Symfony-specific!) questions. In a standard format, it might allow people to easily see the wide range of people in the community and also find there are people with familiar experiences - I'm newcomer, I like the console component too - that type of thing.

**Comment by magnusnordlander** [comment]
@patrickvale: Not to come off as snarky, but I'm well aware of the complexities of doing high-quality remote interviews. In addition to being a host, I also both edit and handle the tech for [Sound of Symfony](https://www.soundofsymfony.com/).

**Comment by patrickvale** [comment]
@magnusnordlander no snarkyness taken - I listen to Sound of Symfony! I am also all for the possibility of doing written or audio, and I guess I'm more inclined to the written ones (perhaps because I got scared off the audio tech!)

**Comment by lsmith77** [comment]
Do we have anyone with experience on how to conduct such interviews and put them together? I guess it probably requires at least 2 people .. ie. one interviewing and the other taking video.
