### ISSUE TITLE
Slack community join link not working

### ISSUE THREAD

**Issue by amanangira** [symfony/diversity#116]
Link - https://symfony-devs.slack.com/join/shared_invite/enQtOTU3MTg2MzA4NzExLWRlNjhiODI3ZGM5ZTk4ZDYxOTNkNmI3ODM3MjMzODVlNGIyZGQ3MjBjMTNlN2Q1ZTYwYTBlM2Y0M2Y1MjlhY2I

**Comment by lsmith77** [comment]
sorry we totally didn't notice this ticket.

where did you notice this issue?

**Comment by brtsos** [comment]
@lsmith77 Slack url doesn't work on community site: https://symfony.com/community.

**Comment by lsmith77** [comment]
are you referring to https://symfony.com/slack ? what are you seeing when you click on that?

**Comment by brtsos** [comment]
Yes. I see that warning when I'm trying use google account:
"Invitation expired
It looks like you’re trying to accept an invitation, but the link was deactivated.

Contact the person who originally invited you about getting a new link or manually inviting you."

**Comment by brtsos** [comment]
I'm seeing that my browser show wrong time. That can be a problem. I will check it :)

**Comment by lsmith77** [comment]
ok .. tried to reproduce the issue in a private browsing session and all seemed to work ..

**Comment by ol0lll** [comment]
The link on the community page:  https://symfony.com/slack redirects to https://symfony-devs.slack.com/join/shared_invite/zt-mdkk6p9f-K9tCmVBykO4w9ypjSFRpqg#/ which shows "This link is no longer active".

**Comment by javiereguiluz** [comment]
@ol0lll sorry about that! There's a problem with the URL redirection (we're taking a look into it at this moment). Meanwhile, this is the URL that you can use -> https://symfony-devs.slack.com/join/shared_invite/zt-o2tdcgkh-fmr7bHYBO5T5LpV9QqjSDg#/

**Comment by ol0lll** [comment]
@javiereguiluz No worries, thanks a lot!

**Comment by amanangira** [comment]
I think this can be closed now.
