### ISSUE TITLE
mentorship program

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#14]
In general we could also have a less formal mentorship program where we simply try and connect people to are looking for mentorship with people that have a few hours to share. That being said I think this would also require some ground rules and learning material for potential mentors.

**Comment by lsmith77** [comment]
http://php-mentoring.org

**Comment by lsmith77** [comment]
some other options https://railsgirlssummerofcode.org and https://www.outreachy.org

**Comment by lsmith77** [comment]
@nicolas-grekas signed us up for https://teams.railsgirlssummerofcode.org/projects/221-symfony based on the request by @dunglas

**Comment by nicolas-grekas** [comment]
If it can give ideas to others, I'm going to mentor someone in our Paris offices in two weeks: some unsold days of a guy are going to be spent next to me, contributing on Symfony or related things. Could for for more :)

**Comment by stof** [comment]
https://teams.railsgirlssummerofcode.org/projects/221-symfony is still marked as pending on their website. what is the status @nicolas-grekas ?

**Comment by javiereguiluz** [comment]
In order to have diverse points of view about our initiatives, I'm sharing this article about a LLVM project contributor that left the project because LLVM associated with outreachy.org (which was also mentioned in a comment above). According to him, Outreachy is an organization that *"openly discriminates based on sex and ancestry"* and that *"goes directly against my ethical views"*.

https://lists.llvm.org/pipermail/llvm-dev/2018-May/122922.html

**Comment by javiereguiluz** [comment]
Another example of a successful mentoring initiative in tech projects: "RustBridge" (https://rustbridge.github.io/)

> RustBridge is a workshop focused on getting underrepresented people with a background in another programming language to learn Rust and join the community.

**Comment by lsmith77** [comment]
@dunglas I guess @nicolas-grekas has had quite a bit of success here. any thing we can do to maybe formalize this a bit more? or rather what can we do to make this more visibile and potentially grow the mentors.

**Comment by ElectricMaxxx** [comment]
Would `ConferenceBudy` a tool to share possibilities to become a mentor of a single group. maybie guter  0.50 event knife 






Never looked in that.

**Comment by lsmith77** [comment]
I like the idea of conference buddies .. in general I think networking should be one of the key focuses of conferences and networking buddies can not only help deal with anxiety, they can also help a lot with networking.

**Comment by lsmith77** [comment]
https://codingcoach.io/

we have the mentoring slack channel which we also mention in the docs.
