### ISSUE TITLE
use networks to improve (speaker) diversity

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#16]
There are also networks to use to seek out potential speakers from underrepresented groups. For women there is for example https://speakerinnen.org/en.

**Comment by lsmith77** [comment]
another org for female speakers http://www.womenpresent.com

**Comment by javiereguiluz** [comment]
Next Saturday 3rd February there is a Global Diversity CFP Day (https://www.globaldiversitycfpday.com/):

> On Saturday 3rd February 2018 there will be numerous workshops hosted around the globe encouraging and advising newbie speakers to put together your very first talk proposal and share your own individual perspective on any subject of interest to people in tech.

**Comment by iltar** [comment]
I would like to add this website to the list: https://www.techgirl.nl/. Techgirl is a website that targets the female audience with with technology related to (amonst others) lifestyle, fashion, etc. While it's not be the direct audience for (symfony related) speakers or software engineers, it might be possible to still reach a larger audience for diversity.

**Comment by ElectricMaxxx** [comment]
So it is mine now :-)

I organize just a smal side track on FrOSCon conference in germany, but i will try to contact the networks here and have a look if there is something more.

More later .. :-)

**Comment by ciaranmcnulty** [comment]
I'm sure http://phpwomen.org could help out

**Comment by ElectricMaxxx** [comment]
Thanks for the input.  We should track those links for each group we wanna address. Tracking them doesn't mean for me to have them in an issue as quering issues isn"t that nice. So any ideas?
Second question would be (and i made that question in chat also): how to contact those groups in a way not to hurt the members by simply asking the wrong question with the wrong words?

**Comment by ElectricMaxxx** [comment]
Currently we do have women networks only, but diversity is quite more then women. Do you know some more and other networks?

**Comment by lsmith77** [comment]
list of female speakers https://github.com/fempire/women-tech-speakers-organizers

**Comment by javiereguiluz** [comment]
Here is a strong candidate for the new speaker list: Victoria Quirante (@VictoriaQ). She's a talented PHP/Symfony and JavaScript developer, she cofounded her development company, she's an experienced speaker (she has delivered lots of talks in local Symfony conferences and meetups), she speaks (at least) Spanish, English and German, etc.

**Comment by ElectricMaxxx** [comment]
I will open my own little cfp next days. I will try to get in contact with the networks by a kind of an inferview. I would just need some creative and gramma help. At end i simply whant to know, which parts are responsible not to propose a talk. But making that question direktly will bring lots off pain, isn't it. So lets create a questionaire, where we will be able to get our answers.

**Comment by lsmith77** [comment]
https://airtable.com/shrhKvKMEnxVJAPw1/tblfomVkRxAWhKxqz

**Comment by ElectricMaxxx** [comment]
i am back here :-)
i would like to start creating a kind of an questionaire for an interview tonight, someone has some hints?
I would try to get a contact with such an interview.

**Comment by lsmith77** [comment]
was this comment meant for https://github.com/symfony/diversity/issues/11 ?

**Comment by ElectricMaxxx** [comment]
@lsmith77 no. I wrote some comments above that i whant to try to get in touch with the networks by simply asking questions. So i have the idea in my head to create an interverview and ask for participants on twitter.

Whit the question i want to:

- get in touch
- get to know barriers 
- get to know sources for their meetings
- ask for specific behavior they whish or simply traps i can fall into

**Comment by ElectricMaxxx** [comment]
And yes afterwards i would like to share the interview by one ore more blog posts.

**Comment by ElectricMaxxx** [comment]
I did not get it (no time) to create a kind of an interview to get in touch whith the networks above. But i started pointing theme one by one on twitter to  my CfP and simply asking for barriers a conference organizer can create to exclude members of thier network. Maybe i get some insight then.

**Comment by ElectricMaxxx** [comment]
Yea i wanna give a state here:
I really tried to reach several groups during my cfp process of for FrOSConPHPTrack at the end i have one single women in my schedule. And that is a collegue of mine, which i supported that long until she says "yes" *g*. No at the end she is really happy that i gave the background she needed and her topic is really interessting at all. 
That said i musst say: i failed. and it bekomes reality when having a look into the twitter interaction:
![selection_335](https://user-images.githubusercontent.com/2905834/44296240-ceaf1e80-a2ba-11e8-9f3c-9bc94c987f82.jpg)
That is not that much at all, but the relation is really bad. 8% interaction with females. Having that number in mind i do not have to concern about it.
What did i do: I tried to connect to sevaral "women in tech" networks like:

- @WomenWhoCode
- @Womenintech
- @WTWomen
- some groups mentioned here

I had positive contact to one or two of them which shared my cfp. I also asked for some kind of interview (just talking about cfp's or conferences) but there i got no answer, except "we look for some one who can make it" and there is sill wait for answer.

At the end i do have the next CfP i am mentoring (Code Talks in Hamburg, "Buzzing Technologies" Track). There i also tried to get in touch with that active groups, but now i have no answer. 
So what to do? Directly write to the devs in that excel sheet @lsmith77  gave me? Writing a blog post with some one more sensible in english language?

**Comment by lsmith77** [comment]
closing in favor of #64
