### ISSUE TITLE
mentor new conference speakers

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#17]
One of the most effective ways to help grow your network and reach within a community is to give a talk at a conference but it can be intimidating and also it can be hard to get talks selected without a track record. So I have already successfully gotten people on the speaker bandwagon by simply having them join me on stage as a co-speaker (for example Jordi did his very first talk as a co-speaker with me back in 2009 at Symfony Live Paris). Now I do realize that for conference organizers it's not so easy to just double their speaker expenses, so we might also need some sort of financial assistance from the community to make it work.

**Comment by nicolas-grekas** [comment]
For reference, for SymonyLive Paris, I took the time to help almost all speakers (@dunglas helped also). Several are first time speakers.

**Comment by javiereguiluz** [comment]
Not specifically about "mentoring speakers", but this resource shows a successful case study of mentoring people in conferences (not to be speakers but developers): https://www.palantir.net/blog/making-inclusion-happen-through-mentoring It also shows that mentoring is very expensive in resources such as time and money.

**Comment by ElectricMaxxx** [comment]
What about introduction of newcomer slots with other speakers attending and giving feedback?

I would also encourage to start in local UGs.  We could organize extra slots there also, especially on SF UGs.

**Comment by ElectricMaxxx** [comment]
I really really forced to talk to new and un-experienced speakers during the CfP of my (PHP Side Track at frOSCon)[http://cfp.froscon-php-track.de]. At the end (CfP closes on saturday the 30th), i have on new speaker in my list. And this is a local collegue of mine. 
So having a CfP and simply announce to support new speakers i not enough. The barrier to approach a CfP of a bigger conference seams to be higher. What to do else? I spoke with some collegues and some points where saying:

- No idea of a topic (while working on really interessting stuff)
- The expected level they have to serve is to high
- preparing  an abstract and talk it self takes quite longer for unexperienced speakers

So any ideas to solve that issues?

**Comment by iltar** [comment]
On slack we have a new channel called `#speaker-mentoring` which seems to aim at partially solving some of your points. There are a few people that have offered to do mentoring in there, so perhaps we can aggregate them into a list and add them here? Slack has a 10k message limit, so I will mention them here before the information is lost:
 - @nicolas-grekas 
 - @simperfit
 - @ciaranmcnulty

**Comment by ElectricMaxxx** [comment]
You can add mee too.

**Comment by dunglas** [comment]
I can do it too

**Comment by lsmith77** [comment]
me as well

**Comment by ElectricMaxxx** [comment]
We should also be visible beside a CfP. This years conferences closed this week. But we should be visible on the next one. 
And i must say, giving a hand very close before and while speaking is different to bringing confidence to start writing an Abstract. This is the higest barrier (listed some reasons above)

**Comment by lsmith77** [comment]
we want to integrate some content around this into the lightning talks https://github.com/symfony/diversity/issues/55

furthermore we could provide some workshop as part of the #32 

continuing this topic in the above tickets.
