### ISSUE TITLE
offer university training event during SymfonyCon Lisbon in 2018

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#18]
From what I hear universities in Lisbon have quite an ethnic mix with quite a few students coming from Africa. Maybe we could collaborate with local universities to either organize a training or simply invite students to join the hackday?

**Comment by dcsg** [comment]
@lsmith77 this is a great idea. If you want, you can assign this to me. How do you want to discuss ideas around this?

**Comment by lsmith77** [comment]
you should have received an invite, as soon as you accept, feel free to assign the ticket to yourself. as for discussion, maybe join #diversity on the symfony slack?

**Comment by tiagobrito** [comment]
Does this apply only to Lisbon Universities?

**Comment by lsmith77** [comment]
the idea is to use the fact that we will have several people that can help on site with SymfonyCon. of course we could organize such things with other universities, but that would then require getting enough experienced people there to do the training.

**Comment by dcsg** [comment]
@lsmith77 already contacted a professor from one university here in Lisbon. As soon as I got a reply from him I will let you know.

**Comment by lsmith77** [comment]
awesome!

**Comment by ElectricMaxxx** [comment]
I think this is cool. Any infos still there? Or shall we wait until conference is finalized. There still is no cfp for us.  What about doing samw for youth. 

When we find some sponsoring for vacation i will be there for kids and students.

**Comment by lsmith77** [comment]
@dcsg ping .. did you have a chance to look into this? any help needed?

**Comment by lsmith77** [comment]
updated the title for Amsterdam :)

**Comment by lsmith77** [comment]
actually lets move this to a new ticket #42
