### ISSUE TITLE
create a CoC enforcement group

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#2]
We need to come up with a structure for a team to handle any code of conduct violation reports. For this we might want to study how other OSS projects do this. For example Drupal has this process:
https://www.drupal.org/governance/community-working-group

**Comment by lsmith77** [comment]
some advice on how to deal with CoC  violation reports:
https://frameshiftconsultingdotcom.files.wordpress.com/2016/03/conferenceincidentresponseguide.pdf

**Comment by lsmith77** [comment]
here is another useful link http://files.frameshiftconsulting.com/codeofconducttraining.pdf

**Comment by javiereguiluz** [comment]
A person from Mozilla has published: [How We’re Making Code of Conduct Enforcement Real — and Scaling it.](https://medium.com/mozilla-open-innovation/how-were-making-code-of-conduct-enforcement-real-and-scaling-it-3e382cf94415). Their process looks great ... but incredibly huge and complex to setup. Maybe for their colossal size is OK, but for smaller projects like Symfony may be too much.

An interesting conclusion of their process: "People prefer to report anonymously".

**Comment by lsmith77** [comment]
very interesting find!
