### ISSUE TITLE
check symfony.com for accessibility for colorblind people

### ISSUE THREAD

**Issue by dbu** [symfony/diversity#21]
color blindness or the inability to distinguish red and green affects quite some people. is symfony.com optimized for this? if not, we should run a tool and fix issues.

**Comment by javiereguiluz** [comment]
I'd live to give more context about this: red vs green is just one of the many color blindness types: https://en.wikipedia.org/wiki/Color_blindness

**Comment by xabbuh** [comment]
Are there tools that can be used to do some automatic checks?

**Comment by lsmith77** [comment]
this might help https://www.liip.ch/en/blog/accessibility-with-a11ym

**Comment by javiereguiluz** [comment]
I've just run a11ym on symfony.com:

![a11ym-report-result](https://user-images.githubusercontent.com/73419/34727610-c7bfcaa4-f557-11e7-8286-901328b4b20d.png)

Now, let's fix some of those errors!

**Comment by javiereguiluz** [comment]
Yesterday we changed some colors to increase contrast and did some other quick changes. That fixed around 6,000 issues:

![ay11m-report](https://user-images.githubusercontent.com/73419/34761444-1ee45a0c-f5e4-11e7-82dc-bcde9965530b.png)

**Comment by stof** [comment]
@javiereguiluz is there any new progress on this topic since the last time you published the report summary ?
What kind of errors are the remaining ones ?

**Comment by stof** [comment]
Btw, speaking about color blindness support, we should probably also run a similar analysis on the web profiler UI.

**Comment by lsmith77** [comment]
@stof (or anyone else interested) I can add you to the automated monthly check I setup.

**Comment by ElectricMaxxx** [comment]
Can we port the issues to a board, pls? Maybe with some prio.

**Comment by javiereguiluz** [comment]
I've just checked and we're down to 2,300 errors (5,193 errors last time we reported it here). We can't fix all errors at once, but the trend is clear and we're fixing them steadily:

![a11ym-errors](https://user-images.githubusercontent.com/73419/38464889-4c368810-3b15-11e8-8d1e-277751150e4a.png)

**Comment by lsmith77** [comment]
@ElectricMaxxx I have invited you to the web UI. 

BTW if anyone else wants access, just let me know
