### ISSUE TITLE
guidelines for receiving feedback

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#23]
This is sort of the companion topic for #4 .. it would give people advice on how to receive feedback on reviews, ie. encouraging them to contribute. Make it clear that all contributions go through a rigourous process but that it is intended to be a positive learning experience for all involved. Also things like that any criticism is does not automatically mean that changes should be implemented because one persons opinion alone is usually not relevant. Maybe also have a link to the core contributor team so that they know who the people are that can merge.

**Comment by javiereguiluz** [comment]
About this:

> Also things like that any criticism is does not automatically mean that changes should be implemented because one persons opinion alone is usually not relevant.

This is not what usually happens in Symfony repo and we even discourage it in the new "give feedback" guide. We literally say that you must always give technical reasons, not opinions. Comments like *"I don't like this"* will be ignored, whereas *"This is not correct because XXX and YYY"* must be taken into account.

**Comment by lsmith77** [comment]
Yeah but imho it would still make sense to adress this from both “sides” because there will of course always be cases where the feedback will not be formulated ideally.

**Comment by GawainLynch** [comment]
I agree with @lsmith77 here. We can have all the guidelines in the world to detail _how_ people should provide feedback, but people are going to "people" :innocent: … and as such it is important to recognise that even with the purest intent it is not always easy to interpret another person's actions especially when you don't know them well.

If, for example, Lukas would say to me that he did not like something on my latest PR, I would, of course, interpret that as his opinion. However, I would also probably see that as a critique possessing subtle context that I would try to think through (the comment box would have "contributor" or "member" on it, so he must be important, right?). Furthermore, if I wasn't aware that his opinion was not that of a maintainer requesting changes, I would try to adapt my PR accordingly.

**Comment by ElectricMaxxx** [comment]
In general giving feedback is better from the "I perspective". So saying "that is completely wrong" a sentese like "in my opinion this could be solved in an other way, lets have a look into best practices/guidelines/docs/examples ... ".
Saying that i think we should have a look on both sides of feedback, especially in a code review.

**Comment by ElectricMaxxx** [comment]
Sorry, took a while. I will add some insights here, when we do have our company barcamp in june. I just need to collecr it and write it down there.

**Comment by TimoBakx** [comment]
The docs have been updated and a blog post has been released here: https://symfony.com/blog/giving-and-receiving-feedback
