### ISSUE TITLE
Male fallback profile pictures on contributors page

### ISSUE THREAD

**Issue by derrabus** [symfony/diversity#25]
I've read the blog article about [making SensioLabs Connect more inclusive](http://symfony.com/blog/making-sensiolabs-connect-more-inclusive) and I understand why the white male default pictures have been problematic.

The [Symfony contributors page](http://symfony.com/contributors/code) seems to reuse the profile pictures from SensioLabs Connect. However, in that list there a some contributors without a Connect profile. Apparently, the code behind the page falls back to the old default picture from Connect. This should probably be adjusted as well?

I'm not sure if this is the right place to report that issue. If not, please point me into the right direction and I'll close this ticket.

**Comment by fabpot** [comment]
I've done similar changes now. Thanks for reporting.

**Comment by fabpot** [comment]
By the way, I've done the same changes for the Silex's and Twig's websites.

**Comment by derrabus** [comment]
Wow, that was fast. Thanks. 😃
