### ISSUE TITLE
Contribution support

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/diversity#28]
Something like: https://twitter.com/simona_cotin/status/968419418035376128?s=19 in Symfony repos.

**Comment by lsmith77** [comment]
afaik we have something like this already .. @weaverryan ?

**Comment by javiereguiluz** [comment]
We recently introduced the standard GitHub labels `good first issue` and `help wanted` in Symfony Code and Symfony Docs repos. For example:

* Help Wanted in Symfony Code: https://github.com/symfony/symfony/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+
* Good First Issue in Symfony Code: https://github.com/symfony/symfony/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+

-----

In some personal projects I'm testing the creation of curated issues for newcomers. They are actionable and very small in scope. The description of the issue explains what to do, why we do that and where to do it (in which branch). Example: https://github.com/EasyCorp/EasyAdminBundle/issues/2132

**Comment by ElectricMaxxx** [comment]
Looks good, but is that enough? 

I would see some other action items:

*OSS - Why shall i contribute*
At the beginning we must reach those developers/companies, which do not understand the the way OSS works. We (or friendly company/sponsors) should give them a hand maybe by introducing a slack day. Doing so we would increase the amount of possible contributors. Then the labels are really helpfull to lead them throug the issues.
Next to those companies, we should help schools to teach thier students, that the studends understand the way OSS lives diversity. In germany we got the "Code University", which organizes "Code & Design Camps" for students of age 15-20. I where coach in Berlin and i think this can be very usefull. But it is difficult too, cause especially integrating girls into though boy groups istn't that easy.
So education sound more like a thing to support OSS, but teaching the OSS live would give a hand and will end up more contribution

*Shouting it out*

- organize best practices for all symfony ecosystems how to handle new contributions
- anounce the current state
- organize hackatone

*Be aware of families*

- need a way to integrate contributors with family background.
- i.e. flag issues or open WIP PRs
- help contributors with family background (arguing at home for the time investment is different when i write code or when i would organize a kids soccer team)
- organize hackdays with family support – kids areas and support

**Comment by lsmith77** [comment]
so as noted we do have some of those labels for issues.
we also have some guides in our documentation how to contribute, see https://symfony.com/doc/current/contributing/community/review-comments.html + https://github.com/symfony/symfony-docs/pull/11324

as for the hackathon (+ family) topic, lets discuss this further in https://github.com/symfony/diversity/issues/32
