### ISSUE TITLE
Place for comming out or explain your "problems". 

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/diversity#31]
I did it in my company several weeks ago and i have to say: it feels awesome. 
What i mean is to generate a place, where everyone can show its talents  and possible disability. 

Maybe  this idea is not possible vor all developer, but we should give it a try. The reason is a kind of e fear to respond THE questions all the day i.e. 'why is you r walk that strange?' And it would give the others a hint how to interact with you.

**Comment by lsmith77** [comment]
a co-worker of mine suggested we all fill out a manual about ourselves .. 
to manage expectations .. like don't expect me to be on time for meetings before 10:00 am

https://docs.google.com/presentation/d/11D0VUH3gwT-PG-dN8tihrcLWO7CDdW9EfgAWXo-nO18/edit#slide=id.g1ca58be816_0_15

but I think this is a bit ambitious for such a large community.

**Comment by lsmith77** [comment]
we just discussed this idea and we struggle with finding an idea how to best implemented this on the community level compared to the "inter-office" or company level. therefore are closing this issue but very welcome to ideas to implement this. right now our concern is that its very high effort where we are unsure how to make it useful in practice.
