### ISSUE TITLE
Community group?

### ISSUE THREAD

**Issue by Tiriel** [symfony/diversity#34]
Hi everyone!

First, let me say that seeing founding about this initiative at today's Symfony Live Paris, I was super hyped. There have been loads of problems about diversity, inclusivity and "welcomingness" in the PHP community, and I'm really glad that this is tackled on at last and especially by Symfony.

Just for the context, I'm primary a PHP/Symfony dev, but after unsuccessfully trying to get involved in the community, I started to work in the Node.js community here on GH. And to be perfectly honest, I'm currently trying to revive the Diversity Initiative there. So I'm really doped about seeing this here too and I'd like to help if I can!

I browsed a bit the issues and projects of this repo, and I was wondering about some things. I've seen that the projects sections mention community growing, along with several issues. While this seems like a perfectly valid concern to me, I think this should belong in another repo, with a broader scope than "diversity".

Also, the issues about adopting a proper CoC, and having processes about CoC violations, moderations, or such imply a "real" group organization IMHO.

These two points lead me to consider the following question: Wouldn't it be relevant to create some sort of "Community Workgroup", pretty much like it's done in several other OS projects, to manage all these issues and make decisions when there is need to?

I think that a proper organization, a defined group, preferably open and operating with a high level of transparency would be a real prerequisite and would deeply benefit this kind of initiative.

Thanks for reading me, please forgive my English if I made mistakes, and cheers everyone!

**Comment by ElectricMaxxx** [comment]
What i forgot: welcom! You can find us also in #diversity channel of symfony slack.

**Comment by Tiriel** [comment]
Hey! Thanks for your answer!

I completely agree with your analysis. But I don't think this is incompatible with having a community focused group. Although this repo may not be the proper one to make such a proposition, I don't see which one I can post it to.

For the CoC, again, I completely agree. This is a really important statement to make. But a CoC without some kind of moderation team/properly defined violation report process would be detrimental in my opinion.

Is there actual plans to build such process and the team at this moment?

Thanks again!

**Comment by sstok** [comment]
https://github.com/symfony/symfony-docs/pull/9340 👍 more related issues can be found with the diversity label

**Comment by lsmith77** [comment]
the diversity initiative is driven by the goal of in the long run growing the community in size by becoming more welcoming.

at this point project “governance” happens via the core team:
https://symfony.com/doc/current/contributing/code/core_team.html

as for creating another working group .. effectively the people involved in the diversity initiative here or on slack are such a working group .. but not in a formal setting. ie. we do not have decision processes etc. so far I have not felt a need to become more formal .. but we do need to make sure we sustain our momentum ..

**Comment by lsmith77** [comment]
@Tiriel thanks a lot for raising this topic, it could be a great idea on the general slack. this repository is focused on diversity, so more general community growth is out of the scope we have here. if need some more hints on how to proceed, we are however happy to discuss further on the #diversity slack channel.
