### ISSUE TITLE
TourDeSymfonyCon

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#35]
this is not per se a diversity initiative, but it should of course not be in conflict with the diversity initiative. it however aims to strengthen the community.

generally the idea is to travel together to the SymfonyCon, hacking on Symfony topcis along the way and making stops at different user groups to present the results and collect additional community members.

rough plan:

1. stop Paris, arrival in the late afternoon of December 3rd

* potentially two groups joining, one coming via Zurich and another via Frankfurt am Main by train.
* user group meeting in the evening with food

2. stop Barcelona, arrival in the late afternoon of December 4rd

* travel by train
* user group meeting in the evening with food

3. stop Madrid, arrival around lunch of December 5th

* travel by train
* lunch (or lunch to go)

4. stop Cáceres, arrival in the late afternoon on December 5th

* travel by charter bus
* dinner

5. Lisboa, arrival late in the evening of December 5th

* travel by charter bus

—

For this to make sense we need we would need at least 10 people from Paris on words and maybe 20-30 from Madrid onwards.

People could join along the way. Lukas would work with a travel agency he used to work at from Berlin to arrange everything starting from Zurich/Frankfurt to ensure everyone is booked together.

If several people have a different starting point we could see to integrate that into the travel plan.

The goal would be to get sponsors to provide mobile data and maybe someone providing a server with a composer cache and a symfony.com website proxy to offload the mobile data connection.

—

Tasks:

* [x] find travel agency (Lukas)
* [ ] organize user group meetup in Paris
* [ ] organize a hostel in Paris
* [ ] organize user group meetup in Barcelona
* [ ] organize a hostel in Barcelona
* [ ] organize dinner in Cáceres
* [ ] collect list of interested people and their starting points
* [ ] find sponsors for mobile data
* [ ] find sponsor for proxy server

**Comment by lsmith77** [comment]
some challenges:
* how to ensure that the trip is family friendly (ie. partners and children can come along)
* how to ensure CoC during the trip (any additional rules needed to be able to travel and be in such close proximity for up to 3 days?)
* how to provide accomodation?

**Comment by lsmith77** [comment]
as of now there has been little interest in supporting this initiative, so it will likely not happen

**Comment by teohhanhui** [comment]
:crying_cat_face:

**Comment by bmack** [comment]
Sorry to see people mostly "reading" about this idea, but not committing - I did this as well. Great idea, but no definitive answer or commitment.

To spice things up a bit - I'd be in for travelling to SymfonyCon with TourDeSymfonyCon - depending if it's still on.

**Comment by teohhanhui** [comment]
I'd love to go too! I'm new to Europe so it'll be a really great opportunity to see more places.

**Comment by lsmith77** [comment]
closing due to lack of support

**Comment by nicolas-grekas** [comment]
FYI, we're already working on the venue for next year's SFCon. This mean will have one full year to organize initiatives like this one in the community. First time ever! \o/
