### ISSUE TITLE
Encouraging Interaction between People at Events

### ISSUE THREAD

**Issue by zanbaldwin** [symfony/diversity#36]
There seems to be some difficulty with networking at events. Despite the great efforts of a few individuals, it's still hard to get your foot in the door (so to speak). A few conferences I've been to have tried to tackle this in the past, but it's never really felt like it's enough - like it's been organised by a select few without consulting the community, a last minute effort, or only trying one thing to appease a single group.

There are definitely elements of elitism, a sense of *who you know not what you know*, plus on top of the general awkwardness being part of a minority group can make social anxiety worse (I know mine is really bad at conferences, I could go a whole day without speaking to someone).

Just wanted to start this off to see if anyone had any ideas for encouraging interaction between community members at Symfony events? Or to make it easier for people trying to get involved but are discouraged by certain individuals or previous experiences?

**Comment by javiereguiluz** [comment]
Not sure if this is what you're looking for, but last week I discovered the "Docker Pals" initiative: https://blog.docker.com/2018/09/back-by-popular-demand-docker-pals-is-coming-to-barcelona/

**Comment by zanbaldwin** [comment]
That's definitely a good idea! It's something that can be incorporated along with any other ideas :)

**Comment by lsmith77** [comment]
I liked @ElectricMaxxx suggestion of https://conferencebuddy.io but maybe it could be integrated staight into symfonyconnect .. indeed maybe especially for first time attendees we should recommend them to get a conf buddy.

I have also I have seen at conferences where they put a topic on all lunch desks to encourage discussions and they specifically ask speakers to never have more than one at a table.

I also think we should make it possible to print more information onto the badges (relates to #39) to help strike up conversations. for sure the “talk to be about” stickers and “first time attendee” stickers helped already.

**Comment by lsmith77** [comment]
closing in favor of https://github.com/symfony/diversity/issues/81
