### ISSUE TITLE
content on badges

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#39]
a follow up to 
https://github.com/symfony/diversity/issues/37

making it possible to set prefered pronouns on SymfonyConnect so that this can be printed directly on the badge. this can help normalize the declaration of pronouns in the community.

make it possible to add slack/github/twitter handles to the badges. a write in field with pens available could provide a low-tech alternative but could lengthen queues during checkin.

**Comment by iltar** [comment]
I can only imagine the clutter.. What if a QR code could be generated for the handles to direct to your sensiolabs profile? Ofc this would require more customization on what to show on that page, which is currently not possible afaik.

This is more of an eye catcher, but if you could colorize your own QR code and put the pronouns in the center, you could do something like this:

![image](https://user-images.githubusercontent.com/1754678/49639701-ef3aea00-fa0b-11e8-9315-aacd34046b6e.png)

_I quickly created an image with the pronouns in paint, so it can obviously be of a lot better quality!_

Used this service to generate the QR code: https://www.unitag.io/qrcode

**Comment by iltar** [comment]
With the default google camera app, it will automatically detect the QR code and provide a link. All you have to do is tap it and will open the link in your browser. If this would direct you to the sensiolabs profile, further navigation could be done from there; Github, Twitter etc.

![screenshot_20181207-202822](https://user-images.githubusercontent.com/1754678/49668599-f7704500-fa5e-11e8-9506-03b5511b5aa7.png)

**Comment by michellesanver** [comment]
Closing, replacing by #61
