### ISSUE TITLE
improve our reach into communities of under represented groups

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#41]
we have done a lot to improve safety and how welcoming we are over the past year. now we need to begin to actively reach out to communities to make people from under represented groups aware of what we have done in the hopes they will trust us sufficiently and join our communities.

one strategy I heard AFUP is doing is that they have connected themselves with relevant groups in france that address specific communities. we should try to build a relationship with such local organizations in all countries so that if we have a local event, we can directly reach out to them.

**Comment by Nyholm** [comment]
#SymfonyConHackDay2018

**Comment by lsmith77** [comment]
closing as duplicate of https://github.com/symfony/diversity/issues/64
