### ISSUE TITLE
Tables with topics during coffee and lunch breaks on conferences

### ISSUE THREAD

**Issue by TimoBakx** [symfony/diversity#44]
Have topics (preferably including some of the recent talks) on tables, so people can sit there and discuss them over lunch or coffee/tea.

Perhaps let speakers and staff / core members mix a little more, so more discussions with attendees might occur.

#SymfonyConHackday2018

**Comment by iltar** [comment]
What if during dinner/lunch etc, random subject cards would be handed out by the staff/core members to a table where people are gathered and discuss it for like 5 minutes? Staff/core members could participate

**Comment by Nyholm** [comment]
#SymfonyConHackDay2018

**Comment by lsmith77** [comment]
we decided we think this is a low effort, potentially high reward thing. so we will contact Emilie/Anne-Sophie about this one as part of our hackathon ideas email :)
