### ISSUE TITLE
Have preferred pronoun as part of the conference registration & print on badge

### ISSUE THREAD

**Issue by TimoBakx** [symfony/diversity#45]
#SymfonyConHackday2018

**Comment by iltar** [comment]
Related to #39?

**Comment by TimoBakx** [comment]
Yes, although #39 is bigger than that and might not be easily actionable. #39 is a good place for new idea's and discussion.

**Comment by iltar** [comment]
As proposed by Zan on slack, stickers would be a quick solution that work in any scenario. Could create a bunch of stickers and have people put them on their lanyard for example. Badges would be another idea.

**Comment by iltar** [comment]
Now that I think of it, I fear the majority of people won't use the stickers _"because it's obvious what my gender is"_.

**Comment by Nyholm** [comment]
#SymfonyConHackDay2018

**Comment by dbu** [comment]
if its recorded on symfony connect and simply printed on the badge, it would seem very "normal" and not handling of a special case.

**Comment by TimoBakx** [comment]
Indeed. And also, it's very hard to figure out which (and how many) stickers to get in advance of the conference.

**Comment by zanbaldwin** [comment]
I only saw about 15 people with pronoun stickers at this conference (out of ~900). It needs to be mandatory on badges because using the sticker when it’s not required does give a sense of “other” which is the complete opposite of what it’s intended for.

**Comment by zanbaldwin** [comment]
The registration site is closed-source so this is blocked until we get someone with write access to implement this for us. @nicolas-grekas?

**Comment by michellesanver** [comment]
Closed, replaced by #61
