### ISSUE TITLE
Have a map of the conference available

### ISSUE THREAD

**Issue by TimoBakx** [symfony/diversity#46]
Some people had trouble finding the right rooms. And the quiet room was overlooked by a lot of people. The signs were there, but an actual map would be helpful.

#SymfonyConHackday2018

**Comment by iltar** [comment]
For the upcoming location, they have a virtual tour you can take: https://beursvanberlage.com/virtual-tour-through-the-beurs. Not useful as a map, but might be interesting for people to see where it is and what it looks like. The layout it documented here: https://beursvanberlage.com/overview-of-halls-and-rooms but imo isn't easy to understand. Could either work with them to improve it, or make a custom variant and put it in the lanyards.

**Comment by Nyholm** [comment]
#SymfonyConHackDay2018

**Comment by javiereguiluz** [comment]
A map can be useful, but if not possible, please add some large and visible signs on the walls. Something like this:

```
---------------------------------------
|  <-- Quiet Room (Room 202)          |
|  <-- Beginner Track (Room 220)      |
|      Advanced Track (Room 210) -->  |
---------------------------------------
```

**Comment by zanbaldwin** [comment]
There were one or two signs like that dotted about but they were put there by the hotel (they probably already had them). Would be good to have our own so we know everything is planned out well enough.

**Comment by nicolas-grekas** [comment]
Anything that happened "by the hotel", Emilie or Anne-Sophie asked for them before. So that was under control of the organizers for sure.

**Comment by lsmith77** [comment]
handled in #78
