### ISSUE TITLE
improving accessibility in Symfony eco-system

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#5]
Improving accessibility to Symfony content and in bundles and applications based on Symfony. These tool might help here:
* https://www.liip.ch/en/blog/accessibility-with-a11ym
* https://en.wikipedia.org/wiki/Bobby_(software)
* https://dynomapper.com/blog/27-accessibility-testing/246-top-25-awesome-accessibility-testing-tools-for-websites

**Comment by michellesanver** [comment]
No actionable ideas, closing.
