### ISSUE TITLE
[internal] Create labels for issues

### ISSUE THREAD

**Issue by TimoBakx** [symfony/diversity#54]
I'd like to use labels like [discussion] and [actionable].

#SymfonyConHackDay2018

**Comment by zanbaldwin** [comment]
Agree. Because of diversity being such a general topic it would extremely useful to label issues that are actionable and can be picked up by someone.

**Comment by zanbaldwin** [comment]
Perhaps another label that indicates it need authorisation or feedback from a core team member or Symfony/Sensio staff (such as updating live.symfony.com which is closed-source).

**Comment by michellesanver** [comment]
We have labels and people who can make them ;)
