### ISSUE TITLE
creating guidelines and recommendations for events

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#6]
Creating guidelines and recommendations for conferences, user groups and other events. Things like making sure the website avoids f.e. needlessly gendered language or shows no pictures of people with more than the predominant ethnic background. But also hints like pronoun stickers, prayer rooms and child-care options. Furthermore this can include advice about what to ask for to ensure the venue is accessible for wheelchairs and other special needs.

From what I have heard phpWomen has some experience there, since they often get asked to endorse events and have therefore build a list of criteria they check. I am sure for building accessibility there are also some resources to contact.

**Comment by dmclark** [comment]
http://www.adahospitality.org/accessible-meetings-events-conferences-guide/bookn looks to be good start

**Comment by lsmith77** [comment]
Karolina is working on exactly this https://www.patreon.com/karolina

**Comment by lsmith77** [comment]
here is some advice by @thefoxis for organizers on how to be pro-active about diversity:
https://medium.com/@fox/inclusion-has-to-be-proactive-b01a37f85148

**Comment by lsmith77** [comment]
a useful example of an accessability policy
https://2018.cssconf.com.au/accessibility

**Comment by lsmith77** [comment]
another useful resource is the AdaCamp toolkit https://adacamp.org

**Comment by javiereguiluz** [comment]
When comparing what other events offer regarding diversity, please let's always include the ticket price in the comparison.

For example, the DockerCon event provides some of the things mentioned in the AdaCamp toolkit ... but the early bird ticket costs $1,000. Which event does more for diversity? A $250/ticket event with few diversity things ... or a $1,000/ticket event with lots of diversity things, but only for the few privileged people who can afford to attend it?

**Comment by lsmith77** [comment]
for events wanting to provide child care this post might give some hints https://medium.com/leaky-abstractions/conference-childcare-part-1-helpful-thoughts-for-conference-organizers-203d2b34df5b

**Comment by lsmith77** [comment]
see also https://github.com/ContributorCovenant/contributor_covenant/issues/502 about making sure we have an enforcement team for events

**Comment by lsmith77** [comment]
this thread has lots of hints
https://twitter.com/fox/status/984190081073205248?s=21

**Comment by lsmith77** [comment]
https://medium.com/@betterallies/obviousnotobvious-actions-to-create-an-inclusive-tech-event-af0b1119108f

**Comment by lsmith77** [comment]
http://2018.jsconfau.com/accessibility

**Comment by sstok** [comment]
FYI, the first link doesn't work here is the correct one 👍  http://www.adahospitality.org/accessible-meetings-events-conferences-guide/book

**Comment by iltar** [comment]
And to be fair, I can't afford SymfonyCon myself, I can only go if my company sponsors the trip/tickets. I have a decent salary and I live in the west. I can't imagine what the price of SymfonyCon must be for people who earn less. What about people from Africa/Asia that don't have the Dollar/Euro course? 400 euro for us in their own currency rates, could be similar to 4000 euro if you would compare it. I think this is a big obstacle as well.

**Comment by Tiriel** [comment]
I tend to agree with @javiereguiluz anyway. Would it be for SymfonyLive or JSConf or such, I still can't afford the ticket. But I'm more comfortable with having a sponsorship program inviting me on a 300€ ticket than on a 1500€ ticket. This can have a perverse effect in which the sponsored people see themselves as owing something to their sponsor.

But that doesn't mean some ideas can't inspire a set of guidelines. The list at the end of the JSConf/CSSConf article does give some pretty good ideas like CoC for events, non-gendered language and such.

**Comment by lsmith77** [comment]
https://www.alterconf.com/talks/building-accessible-community

**Comment by lsmith77** [comment]
I don’t know how much there really is a correlation between the price of the event and following steps like jsconf/cssconf are doing to increase inclusion.

I guess the following points could limit venue choices which in turn could drive up costs:
* accessable rooms
* gender neutral toilets

The following topics will drive up costs as well:
* accomodating special diets
* speaker package (though most the cost related things are included in symfony live events as well)
* live captioned talks (actually not sure exactly what this means and how its implemented, I guess this could actually be automated to some degree?)

I don’t know how big the impact of this will be.
The rest of the points noted don’t have much to do with the event cost I would say.

**Comment by lsmith77** [comment]
for real time captioning I found this service http://composition.al/blog/2014/05/31/your-next-conference-should-have-real-time-captioning/

**Comment by lsmith77** [comment]
Karolina from CSSConf/JsConf responded to my inquiry regarding how D&I affects ticket costs
https://www.patreon.com/posts/18355327

**Comment by lsmith77** [comment]
If someone is motivated to help, after discussing with some people on the php women slack, we decided for now the focus should be on providing guideance rather than some “official vetting process” for confs.

for this to get started it would be great if some people could help me work through the above links (and maybe additional links you find) to extract into a single document relevant hints. we should always note in the document the source of course.

the idea being that once we have a single document we could go through and compile a proposed list of steps conferences should take.

**Comment by lsmith77** [comment]
https://medium.com/@fox/inclusion-rider-for-tech-conferences-6493ca91009
https://medium.com/@fox/conferences-i-wont-be-speaking-at-a60b9beed97b

**Comment by lsmith77** [comment]
https://github.com/mxsasha/lessobviouschecklist/blob/master/README.md
https://events.linuxfoundation.org/events/open-source-summit-north-america-2018/attend/diversity-inclusion/

**Comment by lsmith77** [comment]
some more links on speaker selection process:
https://opensource.com/article/18/5/ensuring-high-quality-talks-your-conference
http://seagl.org/news/2018/04/09/code_of_practice.html
http://seagl.org/news/2017/08/17/CFP_selection_criteria.html

**Comment by lsmith77** [comment]
https://twitter.com/misprintedtype/status/1002475159238914048

**Comment by lsmith77** [comment]
https://www.patreon.com/posts/inclusive-events-19148031 (requires donating via patreon)

**Comment by lsmith77** [comment]
https://www.kickstarter.com/projects/961164339/community-event-planning-second-edition

**Comment by lsmith77** [comment]
closing in favor of https://github.com/DutchPHPConference/conference-diversity-and-inclusion
