### ISSUE TITLE
[discussion] Are there transcripts or subtitles available for the conference videos?

### ISSUE THREAD

**Issue by TimoBakx** [symfony/diversity#63]
#SymfonyConHackDay2018

**Comment by stof** [comment]
SymfonyCasts plans to provide transcript for the videos when putting them online, as done for all their videos.

**Comment by TimoBakx** [comment]
@stof Can the community help with that? If so, how/where?

**Comment by zanbaldwin** [comment]
I think this has been solved for SymfonyCon Lisbon with the videos being added to SymfonyCasts :+1:

**Comment by TimoBakx** [comment]
Indeed. I'll close this issue.
