### ISSUE TITLE
Conference Website Accessibility

### ISSUE THREAD

**Issue by zanbaldwin** [symfony/diversity#68]
Each conference listed under *Upcoming Conferences* on the [SymfonyLive Conferences](https://live.symfony.com/) website contains exactly the same `alt` text, wrapped in an anchor tag with no `title` set, making each one indistinguishable to a screen reader and useless to anyone with visual impairment.

**Comment by stof** [comment]
The same is also true for the `Register` button: the alt text of the image is only `Register`

**Comment by lsmith77** [comment]
@javiereguiluz could you look into this?

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue! We've just created a pull request for this, so it will be fixed after merging and deploying it. Thanks.
