### ISSUE TITLE
increase the general awareness on the topic of diversity

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#7]
As such it also makes sense to increase the general education on the topic of diversity. In general while I started to learn about the topic I noticed that there are a lot well intentioned people that might end up doing harmful things (like constantly approaching minorities with questions about how to grow their numbers, rather than simply seeing them as peers) or that are in denial that anything could be problematic within their community. As such it would make sense to start encouraging user groups and conferences to feature talks on this topic. Traditionally Symfony conferences have focused on technical topics, maybe it is time we also cover at least a bit of “soft” topics too.

**Comment by ElectricMaxxx** [comment]
yea that is raelly hard as pointing on the theme can be anoying for others. I had the sitation yesterday in an other general chat. A girls related theme was docorated with a princess and i simply asked "why a princess?". Some lines later a colleague asked me to open a `diversity` channel and i thought "yes it really wanted" and invited him. The result was: he doesn't want to join, he only wants to have it out of its view.

**Comment by michellesanver** [comment]
Might also make sense to have a panel during the social?

**Comment by michellesanver** [comment]
Moved this topic to our discussion about the SymfonyCon social. If you have any questions about that, join #diversity on slack.
