### ISSUE TITLE
Slack Invitation Link not working

### ISSUE THREAD

**Issue by zairigimad** [symfony/diversity#70]
Hello, I don't know if I have to report this issue in this Repository or another one, but the invitation link to slack in the website ( Community Tab ) not working!

https://symfony-devs.slack.com/join/shared_invite/enQtNTQyODExNzE3OTIwLWY5NDQwZWViNzAyY2Q2NGRmYjJhYmE1NmYyNDhiZDJmMGEzNTZkMmIzZjU0ZWFhNWMxMmNjMjFmOTUwNTliODM

**Comment by linaori** [comment]
Heya, the link should be updated (soon). In case it's still not working, try this one: https://symfony-devs.slack.com/join/shared_invite/enQtNTcyMTA5MzkxMDMxLTU0YjJkY2MxODM3MGFlNzVkNGM3ODkxMjkyZjNlNTNlZTdhYWIwMWU3MWY2YjhmMmUyYThhMWIyYjYzZjc0MmU

**Comment by fabpot** [comment]
Link updated

**Comment by prodigeris** [comment]
>This invite link is no longer active.

Lemme join!

**Comment by faizanakram99** [comment]
@fabpot 
The link is not working 
https://symfony-devs.slack.com/join/shared_invite

**Comment by fabpot** [comment]
@prodigeris @zairigimad  Link fixed now

**Comment by yanict** [comment]
Looks like it doesn't work again 😬

**Comment by fabpot** [comment]
@yanict Slack is really annoying with the link renewal. New link available now.

**Comment by yanict** [comment]
Thanks!

**Comment by gorenstein** [comment]
It doesn't work again, please renewal.

**Comment by gorenstein** [comment]
It doesn't work again, please renewal.

**Comment by lukewhitmore** [comment]
Could I have another link please? .. it's expired again.

**Comment by amanangira** [comment]
Still not working 
https://symfony-devs.slack.com/join/shared_invite/enQtOTU3MTg2MzA4NzExLWRlNjhiODI3ZGM5ZTk4ZDYxOTNkNmI3ODM3MjMzODVlNGIyZGQ3MjBjMTNlN2Q1ZTYwYTBlM2Y0M2Y1MjlhY2I

**Comment by linaori** [comment]
I have forwarded this, hopefully a new link will be created soon!

**Comment by linaori** [comment]
Update: It's fixed! You can visit https://symfony.com/slack and this will redirect you to the current invite link

**Comment by gorbat-o** [comment]
Hey guys, the link doesn't work anymore :/

**Comment by javiereguiluz** [comment]
The invite link is working again. Thanks!

**Comment by jbenitosantoni** [comment]
It's happening again

**Comment by javiereguiluz** [comment]
It's working again. Cheers!

**Comment by okwinza** [comment]
@javiereguiluz the invite link seems borken again. :disappointed:

**Comment by javiereguiluz** [comment]
The link has been updated. @okwinza thanks for the heads up!

**Comment by mnocon** [comment]
Hi! The "Slack chat" link on the https://symfony.com/community page is not working anymore 😥

**Comment by javiereguiluz** [comment]
@mnocon thanks for the heads up. The link is working again at https://symfony.com/slack

**Comment by macknik** [comment]
The slack link has stopped working.

**Comment by javiereguiluz** [comment]
@macknik sorry about that. It's working again. Thanks!

**Comment by ssi-anik** [comment]
Tried all the links mentioned in this thread, and none of them worked.

**Comment by javiereguiluz** [comment]
@ssi-anik sorry about that. The link is working again at https://symfony.com/slack
