### ISSUE TITLE
Check if Carson can do warnings, and if such, warn on trivial words used in documentation

### ISSUE THREAD

**Issue by michellesanver** [symfony/diversity#71]
#9 https://github.com/carsonbot/carsonbot

**Comment by lsmith77** [comment]
@weaverryan can carsonbot also generate warnings?

**Comment by lsmith77** [comment]
@OskarStar according to Ryan you are already working on a solution to automatically check for specific problematic words?

**Comment by lsmith77** [comment]
here is the tool https://github.com/OskarStark/doctor-rst

**Comment by lsmith77** [comment]
I integrated all the words that David collected in #9 to @oskarstar's tool
