### ISSUE TITLE
collect resources related to diversity

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#8]
Here is a list of some interesting links to start with:
* https://www.youtube.com/watch?v=D3e3V66TH2Y
* https://www.youtube.com/watch?v=CZx7rYoq1Uw
* http://sage.thesharps.us/2016/01/24/scale-improving-diversity-with-maslows-hierarchy/
* http://sage.thesharps.us/2015/10/06/what-makes-a-good-community/
* https://maleallies.com
* http://geekfeminism.wikia.com/wiki/Geek_Feminism_Wiki
* https://www.ashedryden.com/blog/the-ethics-of-unpaid-labor-and-the-oss-community
* https://modelviewculture.com/pieces/the-dehumanizing-myth-of-the-meritocracy
* https://diversity.ucsf.edu/resources/unconscious-bias
* http://meldye.weebly.com/what-is-dmis.html
* https://speakerdeck.com/fox/building-inclusive-communities
* https://www.vox.com/2015/6/11/8761227/you-guys-sexism-language
* https://frameshiftconsultingdotcom.files.wordpress.com/2016/03/conferenceincidentresponseguide.pdf
* http://files.frameshiftconsulting.com/codeofconducttraining.pdf
* https://medium.com/@fox/when-a-code-of-conduct-becomes-harmful-1d4e737ff7aa
* https://www.ashedryden.com/blog/codes-of-conduct-101-faq
* https://philsturgeon.uk/2016/09/15/codes-of-conduct-maybe-theyre-not-so-bad/

**Comment by lsmith77** [comment]
related to #7

**Comment by lsmith77** [comment]
As a less formal way to exchange knowledge I think it might make sense to have a channel dedicated to link exchanges on the topic of diversity where all discussion would happen in threads so that anyone joining the channel is simply presented with a list of links and discussions on said links. 

However before we do this we would need to add https://slackarchive.io or something similar to get an archive of our discussions. That being said, maybe we should look into alternatives to Slack anyway, since their interfaces is not accessible, ie. not compatible with screen readers.

**Comment by zanbaldwin** [comment]
Mentioned in the Slack channel:
- https://opensourcediversity.org/ 
- https://drnikki.github.io/open-demographics/
- https://chaoss.community/metrics/
- https://up-for-grabs.net/#/

**Comment by michellesanver** [comment]
Closing in favour of #62
