### ISSUE TITLE
SymfonyCon Amsterdam social event organization

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#86]
issues with past events:

* loud music makes it hard to network and talk
* difficult to get there
* lack of sitting
* lack of non-alcoholic drink options
* free drinks are aloholic
* water bottles should be easy access
* people leaving early
* requirement to wear a t-shirt to join social (and lack of cut options)
* 3rd party security

solutions:

* social should be close to the conf venue
* other forms of entertainment than music
    * board games
    * role playing group
    * scavenger hunt (finding out details of attendees, taking a photo in a specific location etc)
    * murder mystery
   * start the social with a panel discussion
     * allow the audience to participate by using the “empty chair rule”
* focus more on non-alcoholic drinks

challenges:

* how to get the board games? (@TimoBakx) 
    * sponsors (local board game store?)
    * board game winners get to keep the board game?
    * check with @skoop 
* integration attendee details in the scavenger hunt would require some sort of survey
* murder mystery (@michellesanver)
    * Michelle asks php|tek
* in the center of Amsterdam
    * lots of other options for entertainment
    * so get people hooked early
* for logistical reasons it makes most sense to use the conf location (@michellesanver) 
    * ask anne-sophie / emilie about the location
    * how many usually attend the social
        * budget
        * how many people usually attend
    * there should be big enough rooms

**Comment by skoop** [comment]
@lsmith77 For the DPC game night I bring games from my own collection (and suggest to attendees to bring their own games if they want to and provide storage for the duration of the conference). I know that Ross, Aisha and Lucas had a deal with a local game store for the DomCode game night. I'd be happy to help/host a game night.

As for locations, Aisha and @rdohms could be helpful. They've hosted several game nights for AmsterdamPHP IIRC.

**Comment by lsmith77** [comment]
closing in favor of https://github.com/symfony/diversity/issues/102
