### ISSUE TITLE
review content on symfony.com

### ISSUE THREAD

**Issue by lsmith77** [symfony/diversity#9]
It might also make sense to review the content we have on symfony.com. Efforts have already been done to change the language in the documentation to not use gendered pronouns, removing belittling filter worlds like “just” or “easy”. While there is always room for improvement, other areas have not yet been looked at so closely, like for example the imagery and language we use outside of the documentation.

**Comment by sstok** [comment]
Is there a general style guide for grammar/speech?

https://www.dal.ca/webteam/web_style_guide/writing_for_the_web/structuring_content.html
https://www.dal.ca/webteam/web_style_guide/writing_for_the_web/tone_voice.html

**Comment by dbu** [comment]
some further input on particular words in this tweet discussion: https://twitter.com/dshafik/status/949026730005549056

**Comment by dbu** [comment]
@weaverryan i plan to finally pick this up in the next days. in a first iteration, i plan to hunt for the words from https://twitter.com/dshafik/status/949026730005549056 and try to improve passages that go overboard with those. 

1. is it right to do that against master, or should i chose an older branch?
2. i intend to do pull request per chapter / folder to keep the diff manageable. does that seem reasonable to you?
3. any other considerations i should take into account?

**Comment by dbu** [comment]
my keyword list with counts on a naive grep is
* simply: 185 
* just: 439
* easy: 148
* easily: 137
* quick: 83
* of course: 43
* logically: 4
* clearly: 4
* obviously: 3
* merely: 1
* basically: 13
* trivial: 7

i don't intend to eliminate every single occurence of those words, but tone it down where i feel its appropriate.

**Comment by dbu** [comment]
for the documentation part of the website:

* [x] Getting started
* [x] Best practice
* [x] All the smallish stand alone folders
* [ ] Bundles
* [ ] Components

**Comment by dbu** [comment]
I did not see how to do pull requests to symfony.com things outside of the /doc/ path... I just note my change suggestions here, maybe @javiereguiluz can apply them?

https://symfony.com/when-use-a-framework
"Well... Whenever you need to, while developing a web application or a site, of course!"
this sounds pretty pointless. i think we can remove that and just keep the next section with the analogy.

https://symfony.com/six-good-technical-reasons
"Each bundle is intended to add functionality to the framework, of course, and each bundle can also be reused in another project or shared with the rest of the community."
simply remove "of course,"?

*Nothing to do with the subject at hand, but noticed while going through the pages i found on symfony.com*

https://symfony.com/six-good-technical-reasons
"By way of comparison, Symfony is about 3 times faster than Symfony Version 1.4 ..."
search&replace of Symfony2 gone wrong? which version of Symfony is this talking about, 2, 3 or 4? and afaik 3 is much faster than 2 and 4 even faster. might needs to be revised.

https://symfony.com/at-a-glance
"And behind Symfony, there are people. We are the people of SensioLabs."
while this is somewhat true for the initial symfony 2, it is making symfony look more limited to sensio than it actually is. imho this should mention the other contributors, maybe something along "the people of SensioLabs together with contributors from all over the world"...

i found nothing problematic in the https://symfony.com/in-five-minutes section, but think those pages could use some love to improve them in general. they are rather vague to me and not very convincing.

**Comment by javiereguiluz** [comment]
@dbu thanks for reviewing those pages. It's true that there are some old contents that must be reviewed. Meanwhile, I've submitted a pull request to the symfoy.com private repo to do all the changes you proposed here.

**Comment by dbu** [comment]
great, thanks!

imo we can close this issue, unless somebody is aware of other resources that should be reviewed that i missed?

**Comment by lsmith77** [comment]
I will set this ticket to closed .. that being said, this maybe should be reviewed on a regular basis .. hmm maybe we should have a cronjob?

**Comment by michellesanver** [comment]
Close in favour of #62, this ticket is a great resource.
